Repository magento/magento-cloud-components, pull requests merged in 2019-10, with the labels that each got.

#11 MAGECLOUD-3967: Add static and unit tests to magento-cloud-components
  .gitignore
  .travis.yml
  Console/Command/ConfigShowDefaultUrlCommand.php
  Console/Command/ConfigShowEntityUrlsCommand.php
  Console/Command/ConfigShowStoreUrlCommand.php
  Model/UrlFixer.php
  Test/Unit/Model/UrlFixerTest.php
  Test/Unit/phpunit.xml.dist
  Test/static/Sniffs/Directives/StrictTypesSniff.php
  Test/static/Sniffs/Whitespace/MultipleEmptyLinesSniff.php
  Test/static/phpcs-ruleset.xml
  Test/static/phpmd-ruleset.xml
  Test/static/phpstan.neon
  Test/static/static-travis.sh
  composer.json
Labels: approved

#16 MAGECLOUD-4566: Fix failed tests from forked repos in magento-cloud-components
  .travis.yml
Labels: approved, review

#14 Enahcne PHPUnit fixture
  Test/Unit/Model/UrlFixerTest.php
Labels: Release: 1.0.2, community, improvement

#15 Update README.md
  README.md
Labels: Release: 1.0.2, approved
