Repository magento/magento-cloud-components, pull requests merged in 2020-06, with the labels that each got.

#26 SWAT-430: Extended debugging information about cache & indexer invali…
  Model/Cache/InvalidateLogger.php
  Model/Indexation/Logger.php
  Model/Logger/Handler/Debug.php
  Model/Observer/CacheFlushAll.php
  Model/Observer/IndexerStateSaveAfter.php
  etc/di.xml
  etc/events.xml
Labels: Progress: approved, Release: 1.0.4

#20 MCLOUD-6029: Implement New Relic Logs in Context
  composer.json
  etc/di.xml
Labels: Progress: approved, Release: 1.0.4

#28 Update pull request template with doc requirements
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Progress: review, Release: 1.0.4

#29 Merge develop into 1.0
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .travis.yml
  Model/Cache/InvalidateLogger.php
  Model/Indexation/Logger.php
  Model/Logger/Handler/Debug.php
  Model/Observer/CacheFlushAll.php
  Model/Observer/IndexerStateSaveAfter.php
  Model/UrlFinder/Product.php
  Test/Functional/Acceptance.suite.dist.yml
  Test/Functional/Acceptance/Acceptance71Cest.php
  Test/Functional/Acceptance/Acceptance72Cest.php
  Test/Functional/Acceptance/AcceptanceCest.php
  Test/Unit/Model/UrlFinderFactoryTest.php
  codeception.dist.yml
  composer.json
  etc/di.xml
  etc/events.xml
  tests/functional/_data/.gitkeep
  tests/functional/_data/files/debug_logging/.magento.env.yaml
  tests/functional/_output/.gitignore
  tests/static/Sniffs/Directives/StrictTypesSniff.php
  tests/static/Sniffs/Whitespace/MultipleEmptyLinesSniff.php
  tests/static/phpcs-ruleset.xml
  tests/static/phpmd-ruleset.xml
  tests/static/phpstan.neon
  tests/travis/functional.sh
  tests/travis/static-unit.sh
Labels: 1.0, Progress: approved, Release: 1.0.4

#30 Bump version
  composer.json
Labels: Progress: approved

#32 Quick fix for pr from SWAT team
  Model/Cache/InvalidateLogger.php
  composer.json
Labels: 1.0, Progress: approved, Release: 1.0.5
