Repository magento/magento-cloud-components, pull requests merged in 2020-07, with the labels that each got.

#33 Forward-port 1.0 branch
  Model/Cache/InvalidateLogger.php
  composer.json
Labels: 1.0

#31 MCLOUD-6023: Investigate Redis scan keys eviction
  Console/Command/CacheEvict.php
  Cron/Evict.php
  Model/Cache/Evictor.php
  composer.json
  etc/crontab.xml
  etc/di.xml
Labels: Progress: qa in progress, Release Line: 1.0, Release: 1.0.6

#34 MAGECLOUD-6422: NewRelic Log Enricher - Reported Performance Degradation
  composer.json
  etc/di.xml
Labels: Progress: approved
